export const START_QUESTIONNAIRE = "START_QUESTIONNAIRE";
export const NEXT_QUESTION = "NEXT_QUESTION";

export const QUERY_START = "QUERY_START";
export const PASSPHRASE_NOT_FOUND = "PASSPHRASE_NOT_FOUND";
export const QUERY_COMPLETE = "QUERY_COMPLETE";
export const ANGRY_CUSTOMER = "ANGRY_CUSTOMER";

export const QUESTIONNAIRE_FINISHED = "QUESTIONNAIRE_FINISHED";
